# Generated by Django 4.0.4 on 2022-04-26 19:46

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage', models.TextField()),
                ('fond', models.TextField(default=None, null=True)),
                ('inventory', models.TextField(default=None, null=True)),
                ('number', models.TextField(default=None, null=True)),
                ('exodus', models.TextField(default=None, null=True)),
                ('months', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, size=None)),
                ('months_numbers', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, size=None)),
                ('dating', models.TextField(default=None, null=True)),
                ('size', models.IntegerField()),
                ('book_format', models.TextField(default=None, null=True)),
                ('book_type', models.TextField(default=None, null=True)),
                ('file_path', models.TextField(default=None, null=True)),
                ('handwriting', models.TextField(default=None, null=True)),
                ('material', models.TextField(default=None, null=True)),
                ('description', models.TextField(default=None, null=True)),
                ('additional_info', models.TextField(default=None, null=True)),
            ],
        ),
    ]
