# Generated by Django 4.0.4 on 2022-05-02 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_additional_info_alter_book_book_format_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='special_name',
            field=models.CharField(default=None, max_length=512, null=True),
        ),
    ]
