# Generated by Django 4.0.4 on 2022-05-02 20:01

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_book_special_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='months',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), blank=True, default=None, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='book',
            name='months_numbers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=None, null=True, size=None),
        ),
    ]
